name: deploy-toy-website1
on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: SERVICE_PRINCIPAL
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        template: ./Deploy/main.bicep
