name: deploy-toy-website1

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Azure CLI
      - name: Install Azure CLI
        uses: azure/setup-az-cli@v1

      # Log in to Azure
      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }} -p ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Deploy management groups using Bicep and Azure CLI
      - name: Deploy Management Groups
        run: |
          az deployment mg create --location 'East US' --template-file ./Deploy/main.bicep
